version: "3.3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        HOST_USER: ${HOST_USER}
        HOST_USER_ID: ${HOST_USER_ID}
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    restart: unless-stopped
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
    mysql: